# Tests

test-selected:
	clear
	@make spacer
	make -f makefile.test test-ticket-summary

## Ticket

test-ticket-summary:
	go test -v -run TestTicketSummary -count=1 -timeout=5s  ./internal/app/svc/ticketsvc_test.go

