// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api.proto

package v1

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type EventIDReq struct {
	EventID              string   `protobuf:"bytes,1,opt,name=eventID,proto3" json:"eventID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EventIDReq) Reset()         { *m = EventIDReq{} }
func (m *EventIDReq) String() string { return proto.CompactTextString(m) }
func (*EventIDReq) ProtoMessage()    {}
func (*EventIDReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{0}
}

func (m *EventIDReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventIDReq.Unmarshal(m, b)
}
func (m *EventIDReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventIDReq.Marshal(b, m, deterministic)
}
func (m *EventIDReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventIDReq.Merge(m, src)
}
func (m *EventIDReq) XXX_Size() int {
	return xxx_messageInfo_EventIDReq.Size(m)
}
func (m *EventIDReq) XXX_DiscardUnknown() {
	xxx_messageInfo_EventIDReq.DiscardUnknown(m)
}

var xxx_messageInfo_EventIDReq proto.InternalMessageInfo

func (m *EventIDReq) GetEventID() string {
	if m != nil {
		return m.EventID
	}
	return ""
}

type EventRes struct {
	Event                string   `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EventRes) Reset()         { *m = EventRes{} }
func (m *EventRes) String() string { return proto.CompactTextString(m) }
func (*EventRes) ProtoMessage()    {}
func (*EventRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{1}
}

func (m *EventRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventRes.Unmarshal(m, b)
}
func (m *EventRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventRes.Marshal(b, m, deterministic)
}
func (m *EventRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventRes.Merge(m, src)
}
func (m *EventRes) XXX_Size() int {
	return xxx_messageInfo_EventRes.Size(m)
}
func (m *EventRes) XXX_DiscardUnknown() {
	xxx_messageInfo_EventRes.DiscardUnknown(m)
}

var xxx_messageInfo_EventRes proto.InternalMessageInfo

func (m *EventRes) GetEvent() string {
	if m != nil {
		return m.Event
	}
	return ""
}

type EventIndexRes struct {
	Events               []*EventRes `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *EventIndexRes) Reset()         { *m = EventIndexRes{} }
func (m *EventIndexRes) String() string { return proto.CompactTextString(m) }
func (*EventIndexRes) ProtoMessage()    {}
func (*EventIndexRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{2}
}

func (m *EventIndexRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventIndexRes.Unmarshal(m, b)
}
func (m *EventIndexRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventIndexRes.Marshal(b, m, deterministic)
}
func (m *EventIndexRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventIndexRes.Merge(m, src)
}
func (m *EventIndexRes) XXX_Size() int {
	return xxx_messageInfo_EventIndexRes.Size(m)
}
func (m *EventIndexRes) XXX_DiscardUnknown() {
	xxx_messageInfo_EventIndexRes.DiscardUnknown(m)
}

var xxx_messageInfo_EventIndexRes proto.InternalMessageInfo

func (m *EventIndexRes) GetEvents() []*EventRes {
	if m != nil {
		return m.Events
	}
	return nil
}

func init() {
	proto.RegisterType((*EventIDReq)(nil), "v1.EventIDReq")
	proto.RegisterType((*EventRes)(nil), "v1.EventRes")
	proto.RegisterType((*EventIndexRes)(nil), "v1.EventIndexRes")
}

func init() { proto.RegisterFile("api.proto", fileDescriptor_00212fb1f9d3bf1c) }

var fileDescriptor_00212fb1f9d3bf1c = []byte{
	// 167 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4c, 0x2c, 0xc8, 0xd4,
	0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2a, 0x33, 0x54, 0x52, 0xe3, 0xe2, 0x72, 0x2d, 0x4b,
	0xcd, 0x2b, 0xf1, 0x74, 0x09, 0x4a, 0x2d, 0x14, 0x92, 0xe0, 0x62, 0x4f, 0x85, 0xf0, 0x24, 0x18,
	0x15, 0x18, 0x35, 0x38, 0x83, 0x60, 0x5c, 0x25, 0x05, 0x2e, 0x0e, 0xb0, 0xba, 0xa0, 0xd4, 0x62,
	0x21, 0x11, 0x2e, 0x56, 0xb0, 0x30, 0x54, 0x0d, 0x84, 0xa3, 0x64, 0xca, 0xc5, 0x0b, 0x31, 0x29,
	0x2f, 0x25, 0xb5, 0x02, 0xa4, 0x4c, 0x85, 0x8b, 0x0d, 0x2c, 0x53, 0x2c, 0xc1, 0xa8, 0xc0, 0xac,
	0xc1, 0x6d, 0xc4, 0xa3, 0x57, 0x66, 0xa8, 0x07, 0x33, 0x24, 0x08, 0x2a, 0x67, 0x64, 0xcf, 0xc5,
	0x11, 0x92, 0x99, 0x9c, 0x9d, 0x5a, 0x92, 0x5a, 0x24, 0x64, 0xcc, 0xc5, 0xe3, 0x9e, 0x5a, 0xe2,
	0x98, 0x93, 0x03, 0x56, 0x55, 0x2c, 0xc4, 0x07, 0xd7, 0x01, 0x76, 0x9e, 0x94, 0x20, 0x82, 0x0f,
	0xb5, 0x44, 0x89, 0x21, 0x89, 0x0d, 0xec, 0x19, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0xe0,
	0xf4, 0xf2, 0xac, 0xd9, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TicketerClient is the client API for Ticketer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TicketerClient interface {
	GetAllEvents(ctx context.Context, in *EventIDReq, opts ...grpc.CallOption) (*EventIndexRes, error)
}

type ticketerClient struct {
	cc *grpc.ClientConn
}

func NewTicketerClient(cc *grpc.ClientConn) TicketerClient {
	return &ticketerClient{cc}
}

func (c *ticketerClient) GetAllEvents(ctx context.Context, in *EventIDReq, opts ...grpc.CallOption) (*EventIndexRes, error) {
	out := new(EventIndexRes)
	err := c.cc.Invoke(ctx, "/v1.Ticketer/GetAllEvents", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TicketerServer is the server API for Ticketer service.
type TicketerServer interface {
	GetAllEvents(context.Context, *EventIDReq) (*EventIndexRes, error)
}

// UnimplementedTicketerServer can be embedded to have forward compatible implementations.
type UnimplementedTicketerServer struct {
}

func (*UnimplementedTicketerServer) GetAllEvents(ctx context.Context, req *EventIDReq) (*EventIndexRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllEvents not implemented")
}

func RegisterTicketerServer(s *grpc.Server, srv TicketerServer) {
	s.RegisterService(&_Ticketer_serviceDesc, srv)
}

func _Ticketer_GetAllEvents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EventIDReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TicketerServer).GetAllEvents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.Ticketer/GetAllEvents",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TicketerServer).GetAllEvents(ctx, req.(*EventIDReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _Ticketer_serviceDesc = grpc.ServiceDesc{
	ServiceName: "v1.Ticketer",
	HandlerType: (*TicketerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAllEvents",
			Handler:    _Ticketer_GetAllEvents_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api.proto",
}
